### ISSUE TITLE
Grid containers should honnor padding and border properly before layout

### ISSUE THREAD

**Issue by FremyCompany** [FremyCompany/css-grid-polyfill#18]
This would require changes to the general algorithm, to abstract the element real size and use some available size (element real size - border - padding - ...)

**If you want to get this issue fixed for whatever reason, please comment here.** I'll use the comments to prioritize my future work.

**Comment by gaurav21r** [comment]
+1 :+1:

**Comment by RichiCoder1** [comment]
:+1:

**Comment by snuggles08** [comment]
+1 :+1:

**Comment by FremyCompany** [comment]
Okay I'm going to work on this, probably this weekend ;-)

**Comment by FremyCompany** [comment]
Please test whether it fixes your specific issue, if any, and report any bug ;-)
