### ISSUE TITLE
How can I get the polyfill to ignore particular CSS links?

### ISSUE THREAD

**Issue by JonRimmer** [FremyCompany/css-grid-polyfill#21]
I have externally hosted font CSS that is not accessible via CORS. I cannot remove them or host them locally. How can I get the polyfill to selectively ignore them and not try to download them via XHR?

**Comment by FremyCompany** [comment]
You should just add ```data-no-css-polyfill="true"``` on the style/link element.
This behavior works because: https://github.com/FremyCompany/css-grid-polyfill/blob/master/src/core/css-cascade.js#L466 (or, at least, it should; please reopen this issue if if it doesn't)

**Comment by JonRimmer** [comment]
:+1:
