### ISSUE TITLE
Install via bower

### ISSUE THREAD

**Issue by gaurav21r** [FremyCompany/css-grid-polyfill#24]
A Big HI5 to this project :hand: 

A-M-A-Z-I-N-G!

The Future.... Now!

Since this is so cool @FremyCompany , how about making this a bower package and do releases v0.1, 0.2 etc? It'll greatly enhance community participation plus you know the project is mature enough for all that stuff!

**Comment by RichiCoder1** [comment]
:+1: 
Would ask that `bin` be renamed something like `dist` for bower, since bin has a bad habit of coliding or getting ignored.

**Comment by FremyCompany** [comment]
Thanks ♥

I don't see any valid reason not to do this, but I never did it in the past. Is there any resource you would advise me to read to understand better how bower works, and why "bin" is a bad folder name for the output?

**Comment by FremyCompany** [comment]
Something I can't seem to be able to do with "bower" and which I would like is to allow you to depend on both "css-grid-polyfill" and "css-region-polyfill", but get only one file using the "grunt" build included in this project. Sure, I can ignore this and just publish two packages and tell people that if they need more than one polyfill then they can't use bower, but that seems against the point of using bower in the first place.

**Comment by FremyCompany** [comment]
Just to give you an idea of how it works at this point:
https://github.com/FremyCompany/css-grid-polyfill/blob/master/src/requirements.js
https://github.com/FremyCompany/css-regions-polyfill/blob/master/src/requirements.js

On my PC, I've a "css-polyfills" project which contains both "src/core", "src/css-grid" and "src/css-regions" and which build a single "bin/css-polyfills.min.js" file that only has one core running, and not one per project.

I may publish this repo as a bower package but then people would have issues when they need more than one polyfill, and would have to stop using bower at that point. That seems against the point of using bower to start with.

Any idea?

**Comment by gaurav21r** [comment]
Thanks @FremyCompany ! Actually I'm more of a bower *user* than a package maker. Gimme some time, I'll research and let you know. Anyone else in thi sthread have sufficient bower knowledge to help out?

**Comment by FremyCompany** [comment]
I think I'll provide a bower package with just the content of the "bin" folder, for bower users. I'm not satisfied with this, but given the research I did, there's no way to provide what I want with bower. The only thing bower can do is clone a git repo and filter out some files, not bundle resources or run post-install scripts.

The "duo.js" package manager covers my use case way better, but I can't force people to use it. I'll just document that using more than one polyfill isn't supported by bower, and that people should make their "css-polyfills" build using grunt on their own, or use "duo.js" and let it do it for them.

Stay tuned for a bower package during this week-end.

**Comment by FremyCompany** [comment]
Should work using
     bower install css-grid-polyfill-binaries

Please reopen if it doesn't.

**Comment by gaurav21r** [comment]
:+1:

**Comment by FremyCompany** [comment]
Just to make sure, could you check whether you get the recent 1.1.2 update as expected? As I don't use bower, I don' have a project with 1.0.0 installed to make the test.
