### ISSUE TITLE
Layout hangs in some edge cases

### ISSUE THREAD

**Issue by FremyCompany** [FremyCompany/css-grid-polyfill#28]
There's a nasty bug that causes it to never leave that  for(;;)  loop essentially crashing the tab when I hit some resolutions. You can see that here: http://64.207.183.245 (try resizing the window)

-- Original source: 
https://github.com/FremyCompany/css-grid-polyfill/issues/27#issuecomment-124011174

**Comment by FremyCompany** [comment]
I already understood the issue. At some point during layout, it happens the space distributed to all three columns sum up to the space to distribute minus some very small value (~2e-14). This remaining space is a rounding issue, of course, but the condition to stop the loop is that the remaing space to distribute has become lower than or equal to 0 pixels. 

https://github.com/FremyCompany/css-grid-polyfill/blob/master/src/css-grid/lib/grid-layout.js#L1919

The issue is that the space to be distributed is so small that when it is distributed to the tracks, it is ignored due to the limit of precision of the double numbers, so it never vanishes.

A fix would be to ignore any space to distribute whose value is less than a fractional pixel (to be sure, let's say 1/1024px). 

-- cc: @bfred-it

**Comment by bfred-it** [comment]
Great! It seems to work :)

**Comment by bfred-it** [comment]
Can you remove the url from your message?

**Comment by FremyCompany** [comment]
Sure.
