### ISSUE TITLE
Repeat attribute

### ISSUE THREAD

**Issue by itamayo** [FremyCompany/css-grid-polyfill#3]
Some problems relative to 'repeat' attribute. Whenever it is added on the CSS, the web application gives an error on file css-polyfills.js : 4537

Error : undefined function -> toCSSString

It seems that is expects some object and instance of it gets an Array.
I have done a little trick changing code 
```javascript 
value = value[0];
```
But it says that repeat token does not exists =/

**Comment by FremyCompany** [comment]
It's very possible. I upgraded the CSS Parser recently and it generated a few issues. Some functions now return bare arrays instead of TokenList (basically an array having a toCSSString function).

I'm gonna look at the issue, it's probably easy to fix.

**Comment by itamayo** [comment]
thanks ! I am little bit lost =)

**Comment by FremyCompany** [comment]
I merged the changes which accumulated over the last month on multiple devices, and Exemple 15 containing a 'repeat' function is now working on my PC. 

I would like to confirm your case is solved as well. If not, could you provide a repro to me?

**Comment by itamayo** [comment]
This is a picture take it with the demo/example15.html without any change.
![css-cascade-fail](https://cloud.githubusercontent.com/assets/3738104/5717828/f4923ae8-9b06-11e4-8bc6-d92e747bb276.png)

I added to css_cascade.js:726 this:

```javascript
+return value && value.length>0 && value.toCSSString ? value.toCSSString() : '';
-return value && value.length>0 ? value.toCSSString() : '';
```
But I think it is not rendering fine, I mean is not applying a 'repeat' attribute.

![_is_render_fine](https://cloud.githubusercontent.com/assets/3738104/5717831/fb85fb3c-9b06-11e4-8ede-ee47b88ab097.png)

Extra info: Try it on google chrome, chromium and firefox 26 (same issue)

**Comment by FremyCompany** [comment]
I can repro, indeed. It renders fine in IE, which is why I thought the issue was fixed. I'll investigate why Fx and Chrome seems to face an issue here.

**Comment by FremyCompany** [comment]
Could you have a look now? It looks to be working again in Chrome/Firefox.

**Comment by itamayo** [comment]
Good job ! It is working perfect =)
