### ISSUE TITLE
Continuous scroll to top in IE10+

### ISSUE THREAD

**Issue by bfred-it** [FremyCompany/css-grid-polyfill#30]
Apparently the relayout event is being triggered often in IE and so it scrolls to the top each time. It would be great to avoid the scroll everywhere at least. 

Do you see this bug in your demos?

**Comment by FremyCompany** [comment]
I understand the issue. During a relayout, the grid may collapse to 0px height temporarily, causing the page to not feature a scrollbar for a very short time. I can add some code to make sure this won't happen, however.

**Comment by bfred-it** [comment]
Ah, I see, that makes sense

**Comment by FremyCompany** [comment]
Tentative fix:
https://github.com/FremyCompany/css-grid-polyfill/commit/e32c6b9d40c86fa8c0709591cb3ea65690d1a0c3

PS: I also merged this commit into the browserify branch so that you can test using your current setup.

**Comment by bfred-it** [comment]
Thank you so much for this! I'll be testing it in the morning :)

**Comment by bfred-it** [comment]
Cool, this seems to work!
