### ISSUE TITLE
IE11/10 bug: layout okay, but actual elements have no set widths

### ISSUE THREAD

**Issue by fregante** [FremyCompany/css-grid-polyfill#32]
<img width="643" alt="screen shot 2015-08-03 at 01 45 50" src="https://cloud.githubusercontent.com/assets/1402241/9034065/9f61e4b4-3981-11e5-9539-6427da013b9a.png">

I'll try just using IE's own Grid implementation instead of relying on the polyfill (even simply for performance reasons), but I thought I'd tell you about this issue anyway.

**Comment by FremyCompany** [comment]
Thanks, I'll have a look at it. What are the normally-used-css min/max/width+height of the child elements, and what are your grid columns/rows sizes?

    // FWIW I would recommend using the IE's native implementation 
    // whenever possible, too.

**Comment by bfred-it** [comment]
See here: http://staging.toyotahalloffame.com/

The content has no pre-set size, they usually just fill the container

**Comment by bfred-it** [comment]
I ended up removing this polyfill, it made the site unresponsive on mobile. I'd add a notice to the readme about this.

Now I'm using… tables… plus a custom script to move the elements around.

**Comment by FremyCompany** [comment]
This is already art of the current readme:

> Should I use that in production?
> 
> Your call. I wouldn’t say this polyfill is slow by any measure, but your mileage may vary on mobile devices. My advice would be to use the polyfill only on tablets and desktops at the moment, after you have tested the compatibility and performance extensively on a representative number of devices.

**Comment by bfred-it** [comment]
My bad! I had actually edited the comment because I saw that. And really I noticed that the issue was unrelated to the polyfill at all. It was an overlay with a scrollable area that was still activated even with visibility:hidden, it looked like the site wouldn't respond to the first scroll.

**Comment by FremyCompany** [comment]
Glad to see this wasn't an issue related to the polyfill. That being said, I would argue using a custom script may be a better idea at the moment anyway ;-) Given you update the website in real time, could you make a snapshot of it as a static html and send it to me by email so I can debug the IE issue at a later time? You can find my email on my website (my-github-username dot com).

**Comment by Hypnosphi** [comment]
I have an example where childrens explicit widths are ignored: http://codepen.io/anon/pen/bBQbNq
