### ISSUE TITLE
Current Status in relation to official specs?

### ISSUE THREAD

**Issue by kristianmandrup** [FremyCompany/css-grid-polyfill#41]
Please add some kind of status info in the README regarding how well it matches/reflects the official specs as per Q4 2016. Also list any issues outstanding and any edge cases causing problems. Thanks for the great work!

**Comment by FremyCompany** [comment]
The description is still accurate.

Unsupported features are:
* alignment properties
* grid-gap
* subgrid

Known issues are in the issue list.
