### ISSUE TITLE
Layout 4 not working in Firefox 35

### ISSUE THREAD

**Issue by tp** [FremyCompany/css-grid-polyfill#7]
When viewing the [Bootstrap 16-columns grid / Layout 4](https://rawgit.com/FremyCompany/css-grid-polyfill/master/demo/css-grid/layout4.html) in Firefox all the elements in each row are painted in the same spot.

![screen shot 2015-02-03 at 14 11 27](https://cloud.githubusercontent.com/assets/52437/6020637/91ad012a-abae-11e4-8924-e4873bf334a3.png)

**Comment by tp** [comment]
This also seems to apply to Chrome 40. (Missed this earlier because I had "Experimental Web Platform Features" enabled.

**Comment by FremyCompany** [comment]
Thanks for the bug report, I'll have a look at this

**Comment by FremyCompany** [comment]
Much thanks to @itamayo for having a look at this, I've had a very busy week and was planning to have a look at this during the weekend, and it seems like I won't have to ^_^

Please feel free to report any other issue you may find.

Best regards,
François

**Comment by itamayo** [comment]
You welcome, hope you had a great weakend =)
